### ISSUE TITLE
App icon looks too big

### ISSUE THREAD

**Issue by barbosa** [CocoaHeadsBrasil/MuteUnmuteMic#12]
Comparing with others, it looks weird. Maybe we can make it a little bit smaller.

<img width="720" alt="icon at bottom right" src="https://cloud.githubusercontent.com/assets/235208/10794763/b0564946-7d7d-11e5-926e-35eae0ccafa5.png">

**Comment by diogot** [comment]
Makes sense

**Comment by barbosa** [comment]
80% of its original dimension:

<img width="505" alt="screen shot 2015-11-08 at 5 38 25 pm" src="https://cloud.githubusercontent.com/assets/235208/11023180/913b8998-863f-11e5-8507-52dd07c7aa2d.png">
